### ISSUE TITLE
Vulkan Driver

### ISSUE THREAD

**Issue by thatcosmonaut** [thatcosmonaut/FNA3D#9]
If you need help knowing where to start with these, the FNA3D Metal driver is a good reference point: https://github.com/FNA-XNA/FNA3D/blob/master/src/FNA3D_Driver_Metal.c

**Easy**
- [x] `AddDisposeEffect` (claimed by @NoaGleason)
- [x] `AddDisposeRenderbuffer` (claimed by @NoaGleason)
- [x] `AddDisposeQuery` (claimed by @NoaGleason)
- [x] `ApplyEffect`
- [x] `BeginPassRestore` (claimed by @NoaGleason)
- [x] `CreateQuery` (claimed by @NoaGleason)
- [x] `EndPassRestore` (claimed by @NoaGleason)
- [x] `GetBackbufferSize`
- [x] `GetBackbufferSurfaceFormat`
- [x] `GetBackbufferDepthFormat`
- [x] `GetBackbufferMultiSampleCount` (claimed by @NoaGleason)
- [x] `GetBlendFactor`
- [x] `GetMultisampleMask` (claimed by @NoaGleason)
- [x] `GetReferenceStencil`
- [x] `CreateEffect`
- [x] `CloneEffect` (claimed by @NoaGleason)
- [x] `CreateTexture2D`
- [x] `CreateTexture3D`
- [x] `CreateTextureCube`
- [x] `GenColorRenderbuffer` (claimed by @NoaGleason)
- [x] `GenDepthStencilRenderbuffer` (claimed by @NoaGleason)
- [x] `GetMaxMultisampleCount` (claimed by @TheSpydog)
- [x] `GetMaxTextureSlots`
- [x] `GetTextureData2D` (claimed by @TheSpydog)
- [x] `GetTextureData3D` (claimed by @TheSpydog)
- [x] `GetTextureDataCube` (claimed by @TheSpydog)
- [x] `ResetBackbuffer`
- [x] `ResolveTarget`
- [x] `SetBlendState` (claimed by @NoaGleason)
- [x] `SetDepthStencilState` (claimed by @NoaGleason)
- [x] `SetEffectTechnique` (claimed by @NoaGleason)
- [x] `SetMultisampleMask` (claimed by @NoaGleason)
- [x] `SetReferenceStencil`
- [x] `SetStringMarker` (claimed by @TheSpydog)
- [x] `SupportsDXT1` (claimed by @TheSpydog)
- [x] `SupportsS3TC` (claimed by @TheSpydog)
- [x] `SupportsHardwareInstancing`
- [x] `SupportsNoOverwrite`
- [x] `QueryBegin` (claimed by @NoaGleason)
- [x] `QueryComplete` (claimed by @NoaGleason)
- [x] `QueryEnd` (claimed by @NoaGleason)
- [x] `QueryPixelCount` (claimed by @NoaGleason)
- [x] convert all error output to use `FNA3D_Log` functions

**Medium**
- [x] `AddDisposeVertexBuffer`
- [x] `AddDisposeTexture`
- [x] `ApplyRasterizerState`
- [x] `Clear`
- [x] `DestroyDevice`
- [x] `DrawIndexedPrimitives`
- [x] `DrawInstancedPrimitives`
- [x] `DrawPrimitives`
- [x] `DrawUserIndexedPrimitives`
- [x] `DrawUserPrimitives`
- [x] `GenIndexBuffer`
- [x] `GenVertexBuffer`
- [x] `GetIndexBufferData`
- [x] `GetVertexBufferData`
- [x] `SetIndexBufferData`
- [x] `SetVertexBufferData`
- [x]  `VerifyVertexSampler` (claimed by @TheSpydog)
- [x] Remove code duplication from device suitability checks (claimed by @TheSpydog)

**Hard**
- [x] `BeginFrame`
- [x] Fetch and bind render pipeline in BeginRenderPass (partially complete)
- [x] `ReadBackbuffer`
- [x] `SetRenderTargets`
- [x] `SetTextureData2D`
- [x] `SetTextureData3D` (claimed by @TheSpydog)
- [x] `SetTextureDataCube` (claimed by @TheSpydog)
- [x] `SetTextureDataYUV` (claimed by @TheSpydog)
- [x] `SwapBuffers`
- [x] `VerifySampler`
- [x] Finish `BeginRenderPass`
- [x] Batch calls that destroy or free vulkan objects so we don't stall the program before destroys

**ULTRA NIGHTMARE**
- [x] `ApplyVertexBufferBindings`
- [x] `ApplyVertexDeclaration`
- [x] `CreateDevice`
- [x] Support multiple frames in flight

**Comment by thatcosmonaut** [comment]
If you would like to help, please claim a task either by commenting here or notifying me in the FNA Discord server so we don't step on each other's toes. 

Also I would kindly request that you rebase on `vulkan` before submitting your PR for review. Thank you!

**Comment by flibitijibibo** [comment]
Putting together a testing list... this is sorted according to the features that seem to be the biggest pain to get right. These lists ignore user primitives which are automatic "Fucking Dead Mode".

[x] SpriteBatch Only:
- Bleed
- Wizorb

[x] SpriteBatch with Targets:
- Escape Goat 1
- Soulcaster 1/2
- Wyv and Keep
- Bleed 2
- SUMICO

[x] SpriteBatch with Shaders/Targets:
- Gateways
- Rogue Legacy
- Blueberry Garden
- TowerFall Ascension
- Rex Rocket
- Mercenary Kings
- Before the Echo
- Hacknet
- Salt and Sanctuary
- Hidden in Plain Sight
- Quadrilateral Cowboy Art Book
- Bastion
- Owlboy
- Flinthook
- Charlie Murder
- The Dishwasher: Vampire Smile
- MidBoss
- Growing Pains
- Super Bernie World
- Axiom Verge

[x] SpriteBatch with Shaders/Targets/Video:
- Capsized
- A Virus Named TOM
- Dust: An Elysian Tail
- Fist Puncher
- Apotheon
- Cryptark
- The Adventures of Shuggy
- Full Metal Furies

[ ] Custom 2D (Hard Mode starts here):
- Escape Goat 2
- Skulls of the Shogun
- Gnomoria
- SpeedRunners
- River City Ransom: Underground
- Unexplored
- Streets of Rage 4

[ ] Custom 3D (Ultra Nightmare Mode starts here):
- Reus (super fancy 2D projection)
- FEZ
- Murder Miners
- Celeste (the mountain counts as 3D!)
- Flotilla (AKA the point sprite test)
- Little Racers STREET
- Planetfriend
- Simply Chess

Unknown: Everything else in [this list](http://www.flibitijibibo.com/index.php?page=Portfolio/Tools)

**Comment by jqadev** [comment]
@thatcosmonaut there is the sentence `various implementations available at runtime
(including OpenGL, Metal, and Direct3D)` in README. Shouldn't be added here info about Vulkan in your PR https://github.com/FNA-XNA/FNA3D/pull/13?

**Comment by flibitijibibo** [comment]
@jqadev Updated here: https://github.com/thatcosmonaut/FNA3D/pull/49

**Comment by thatcosmonaut** [comment]
The entire API has now been implemented (aside from GetTextureData3D which nobody uses). There are some lingering issues but we can address those on a case by case basis. Closing this issue.
